#!/usr/bin/env python3
"""Build the bundled pronunciation lexicon used by the rhyme analysis.

The committed lexicon (``data/lexicons/pronunciations_cmudict.txt``) is a subset
of the CMU Pronouncing Dictionary trimmed to just the words that appear in the
Mitski corpus, so the file stays small and auditable while the package loads it
fully offline (no network, no extra dependency at runtime).

This script is the reproducible provenance of that file, not something the
package runs. Point it at a full CMU dict and it rewrites the subset:

    # Get the source dict (public domain) once, e.g.:
    #   curl -LO https://raw.githubusercontent.com/cmusphinx/cmudict/master/cmudict.dict
    python scripts/build_pron_lexicon.py --cmudict cmudict.dict

Only the primary pronunciation of each word is kept (CMU alternates are written
``word(2) ...``; those are dropped). Words are normalized with the same
``text.normalize`` used everywhere else so the keys line up with the tokenizer.
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from mitski_analysis import text as T  # noqa: E402
from mitski_analysis.data import load_corpus, repo_root  # noqa: E402

HEADER = """\
# CMU Pronouncing Dictionary subset (corpus vocabulary only)
#
# ARPABET phoneme transcriptions for the words that appear in the Mitski lyrics
# corpus. Used by src/mitski_analysis/text.py:rhyme_summary to detect end rhymes
# by comparing the "rime" (last stressed vowel to the end) of line-final words.
#
# Source:  The CMU Pronouncing Dictionary (cmudict), Carnegie Mellon University.
#          https://github.com/cmusphinx/cmudict
# License: Public domain (CMU's BSD-2-Clause-style permissive license; the
#          dictionary data is free for any use).
#
# Format:  one entry per line, "word<TAB>ARPABET phonemes" (e.g. "light<TAB>L AY1 T").
#          Only the primary pronunciation of each word is kept. Lines starting
#          with "#" and blank lines are ignored by the loader.
#
# Generated by scripts/build_pron_lexicon.py from a full cmudict; edit that
# script (or its input), not this file, to regenerate.
"""


def read_cmudict(path: Path) -> dict[str, tuple[str, ...]]:
    """Parse a full cmudict.dict into {word: phonemes}, primary pronunciation only."""
    pron: dict[str, tuple[str, ...]] = {}
    with open(path, encoding="latin-1") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line or line.startswith(";;;"):
                continue
            # Strip a trailing "# comment" (present in the cmusphinx .dict form).
            line = line.split(" #", 1)[0].strip()
            if not line:
                continue
            parts = line.split()
            word, phones = parts[0], parts[1:]
            if "(" in word:  # an alternate pronunciation, e.g. "read(2)"
                continue
            if phones:
                pron[T.normalize(word)] = tuple(phones)
    return pron


def corpus_vocabulary(root: Path) -> set[str]:
    """Every word token that appears anywhere in the cleaned corpus."""
    corpus = load_corpus(root)
    vocab: set[str] = set()
    for song in corpus["songs"]:
        vocab.update(T.tokenize(song["lyrics"]))
    return vocab


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--cmudict",
        type=Path,
        required=True,
        help="Path to a full CMU dict (cmudict.dict) to subset from",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output path (default: data/lexicons/pronunciations_cmudict.txt)",
    )
    args = parser.parse_args()

    root = repo_root()
    out = args.out or (root / "data" / "lexicons" / "pronunciations_cmudict.txt")

    pron = read_cmudict(args.cmudict)
    vocab = corpus_vocabulary(root)
    kept = sorted(w for w in vocab if w in pron)
    missing = len(vocab) - len(kept)

    with open(out, "w", encoding="utf-8") as f:
        f.write(HEADER)
        for word in kept:
            f.write(f"{word}\t{' '.join(pron[word])}\n")

    print(f"Wrote {out}  ({len(kept)} words; {missing} corpus words not in cmudict)")


if __name__ == "__main__":
    main()
